### ISSUE TITLE
Use Standard Code Style

### ISSUE THREAD

**Issue by nmrony** [nmrony/hlsdownloader#10]
@boushley I am thinking to change the coding style and adopt standard coding style. I am loving the style gradually and already used to it. What do you think? Should I go for it. I have added necessary plugins and a npm script called lint in package.json. You find it in develop branch. Waiting for your call buddy

**Comment by boushley** [comment]
What's the standard style you're planning to adopt? Do you have a PR/branch where you added the plugins etc?

In general having a standard style and tools to ensure it is followed is a good idea.

**Comment by nmrony** [comment]
@boushley for coding style I am talking about this : http://standardjs.com/ and ESLint to lint the code. It is in  **develop** branch. I did not resolve any styling issues yet. Run `npm run lint` to see it in action BTW I strictly follow git-flow to manage my branches. Let me know if you follow anything else.

**Comment by boushley** [comment]
Sure, following those standards seems like a great idea.

**Comment by nmrony** [comment]
Cool.. I will soon make all style issues gone. Thanks @boushley
