### ISSUE TITLE
provide a default callback for assembling chunks

### ISSUE THREAD

**Issue by drzraf** [nmrony/hlsdownloader#18]
ts files alone a quite useless if they does not get assembled.
`startDownload (callback)` may allow for this (if it get the knowledge of downloaded file names)
That would be nice to provide a simple and sane callback function to assemble ts file in the common cases.

**Comment by nmrony** [comment]
@drzraf Thanks for opening issue. You can assemble the downloaded `ts` files with third party softwares. Closing for now. Feel free to open if you have more to discuss.
