### ISSUE TITLE
No valid Downloadable variant exists in master playlist

### ISSUE THREAD

**Issue by kieste** [nmrony/hlsdownloader#6]
I get this error when I try to download a master playlist containing:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=662000,RESOLUTION=640x360
http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=4845944941001&videoId=4845938708001
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=862000,RESOLUTION=854x480
http://c.brightcove.com/services/mobile/streaming/index/rendition.m3u8?assetId=4845945059001&videoId=4845938708001
```

My playlistURL is http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=4845938708001&pubId=68348640001

**Comment by nmrony** [comment]
Thanks for the report I will take a look on it and try to resolve it by this weekend

**Comment by nmrony** [comment]
@kieste Fix landed on develop branch. Need to test more. Plan to publish it by today. As the whole module is rewritten to **ES2015 ** and some breaking changes happened on requiring this I am planning to publish version **2.0.0**.

**Comment by nmrony** [comment]
@kieste New version of this module has been published with fix of this bug. If you face any issue. feel free to comment or open a new issue.

**Comment by kieste** [comment]
Wow, that was a quick fix. Thanks. I will test the new version later this week.

Regards
Steffen

Am 25. April 2016 um 10:03 schrieb Nur Rony <notifications@github.com>:

@kieste New version of this module has been published with fix of this bug. If you face any issue. feel free to comment or open a new issue.
